sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

services:
  - mysql
  - postgresql

env:
  - DB_DRIVER=pdo_mysql DB_USER=root
  - DB_DRIVER=pdo_pgsql DB_USER=phpunit DB_PASSWORD=phpunit

before_install:
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then psql -c 'CREATE DATABASE test_db;' -U postgres; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then psql -c 'CREATE USER phpunit WITH PASSWORD \'phpunit\';' -U postgres; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'; fi"

before_script:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
