sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

services:
  - postgresql

env:
  - DB_DRIVER=pdo_pgsql
  - DB_USER=postgres
  - DB_PASSWORD=postgres

before_install:
  - psql -c 'create database test_db;' -U postgres

before_script:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
