sudo: false

language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install --no-interaction --prefer-source
  - mysql -e 'create database test_db;'

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover
