sudo: required
dist: trusty

language: php
php:
  - 7.1
  - 7.2
  - 7.3


services:
  - mysql
  - postgresql

env:
  - DB_DRIVER=pdo_mysql DB_USER=root
  - DB_DRIVER=pdo_pgsql DB_USER=phpunit DB_PASSWORD=phpunit

before_install:
  # Postgres
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then psql -c 'CREATE DATABASE test_db;' -U postgres; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then psql -c \"CREATE USER phpunit WITH PASSWORD 'phpunit';\" -U postgres; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then psql -c \"GRANT ALL PRIVILEGES ON DATABASE test_db to phpunit;\" -U postgres; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then sudo sed -i 's/trust/md5/g' /etc/postgresql/*/main/pg_hba.conf; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_pgsql' ]; then sudo /etc/init.d/postgresql restart; fi"
  # Mysql
  - sh -c "if [ '$DB_DRIVER' = 'pdo_mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_db;'; fi"
  - sh -c "if [ '$DB_DRIVER' = 'pdo_mysql' ]; then mysql -e \"SET GLOBAL sql_mode ='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'\"; fi"

before_script:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
