# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: edyan/php:7.2
      # - image: mysql:5
      #   environment:
      #     MYSQL_ROOT_PASSWORD: fjkekI8IeufjI8Ue56
      #     MYSQL_DATABASE: test_db
      - image: microsoft/mssql-server-linux:2017-latest
        name: sqlserver
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: rootRoot44root

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Setup Composer
      - run: php -r "copy('https://getcomposer.org/download/1.6.4/composer.phar', '/usr/local/bin/composer');"
      - run: chmod +x /usr/local/bin/composer
      - run: composer self-update

      # Install deps
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # Wait a little mysql ...
      - run: sleep 10
      # Create DB
      - run: docker exec -it sqlserver /opt/mssql-tools/bin/sqlcmd -U sa -P rootRoot44root -S localhost -Q "CREATE DATABASE test_db"

      # run tests!
      - run:
          name: Run tests
          command: vendor/bin/phpunit
          environment:
            DB_DRIVER: pdo_sqlsrv
            DB_PASSWORD: rootRoot44root
            DB_USER: sa
            # DB_DRIVER: pdo_mysql
            # DB_PASSWORD: fjkekI8IeufjI8Ue56
            # DB_USER: root
