services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Load all Commands
    Edyan\Neuralyzer\Console\Commands\:
        resource: '../src/Console/Commands/*'
        tags: ['console.command']
    # And all services
    Edyan\Neuralyzer\Service\:
        resource: '../src/Service/*'
        tags: ['app.service']
        public: true

    # Expression language main service compiled with services below
    Edyan\Neuralyzer\Utils\Expression:
        public: false
