services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']
        Edyan\Neuralyzer\Service\ServiceInterface:
            tags: ['app.service']


    # Load all Console commands
    Edyan\Neuralyzer\Console\:
        resource: '../src/Console'
    # Load all Services
    Edyan\Neuralyzer\Service\:
        resource: '../src/Service'
        public: true

    # Expression language main service compiled with services below
    Edyan\Neuralyzer\Utils\Expression: ~
