services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']
        Edyan\Neuralyzer\Service\ServiceInterface:
            tags: ['app.service']


    # Load all files
    Edyan\Neuralyzer\:
        resource: '../src/{Console,Service}'

    # Expression language main service compiled with services below
    Edyan\Neuralyzer\Utils\Expression:
        public: false
